version: 2

sources:
  - name: sources
    database: data-engineering-zoomcamp-arp
    schema: sources_olist

    tables:
      - name: olist_customers_dataset
      - name: olist_geolocation_dataset
      - name: olist_order_items_dataset
        columns:
          - name: seller_id
            data_type: string
            tests:
              - unique
              - not_null
          - name: order_id
            data_type: string
            tests:
              - not_null
          - name: product_id
            data_type: string
            tests:
              - not_null
      - name: olist_order_payments_dataset
      - name: olist_order_reviews_dataset
      - name: olist_orders_dataset
      - name: olist_products_dataset
      - name: olist_sellers_dataset
      - name: product_category_name_translation
      - name: olist_marketing_qualified_leads_dataset
        columns:
          - name: mql_id
            data_type: string
            tests:
              - unique
              - not_null
      - name: olist_closed_deals_dataset
        columns:
          - name: seller_id
            data_type: string
            tests:
              - unique
              - not_null
        